/* Bitmap fonts taken from the stock RA89R firmware (see ra89r_lcd.md).
 * Layout of both fonts: column-major and page-major, i.e. a glyph is stored
 * as N bytes per 8-pixel page, each byte being one column of that page with
 * bit 0 = the topmost pixel.  That is exactly the order the panel wants, so
 * the tables are used verbatim.
 * The .c files are generated by firmware/tools/extract_fonts.py. */
#ifndef DRIVER_FONTS_H
#define DRIVER_FONTS_H

#include <stdint.h>

typedef struct {
    uint8_t first;              /* first character code */
    uint8_t last;               /* last character code */
    uint8_t stride;             /* bytes per glyph page row (glyph width) */
    uint8_t pages;              /* glyph height in pages */
    uint8_t bytes;              /* total bytes per glyph */
    const uint8_t *glyphs;
} font_t;

/* 8x16, ASCII 0x20..0x7A (stock image 0x08026072) */
extern const font_t font_8x16;
/* 4+1 x 7, ASCII 0x20..0x5A -- the stock channel display font (stock image
 * 0x08026622) */
extern const font_t font_5x7;

#endif /* DRIVER_FONTS_H */
