#!/usr/bin/env python3
"""
extract_fonts.py -- pull the stock RA89R text fonts out of a decoded image.

    python3 firmware/tools/extract_fonts.py work/FIRMWARE_RA89R_20260203_V49.bin

Two bitmap fonts were located in the stock firmware by reverse engineering
(see docs/ra89r_lcd.md): an 8x16 font used for normal text and a 4+1 x 7 font used
for the large channel display.  Both are stored column-major, page-major with
bit 0 = topmost pixel of the page, which is exactly the layout the ST7565-style
panel wants, so they can be written out byte for byte.

Produces firmware/App/driver/font_8x16.c and font_5x7.c.
"""

import argparse
import os
import struct
import sys

MAGIC = b"RA89RMETA3"

# (name, address in the stock image, first char, last char, bytes per page row,
#  pages per glyph)
FONTS = [
    ("font_8x16", 0x08026072, 0x20, 0x7A, 8, 2),
    ("font_5x7", 0x08026622, 0x20, 0x5A, 5, 1),
]


def load(image_path, meta_path=None):
    with open(image_path, "rb") as f:
        data = f.read()
    meta_path = meta_path or image_path + ".meta"
    with open(meta_path, "rb") as f:
        blob = f.read()
    if not blob.startswith(MAGIC):
        raise SystemExit("%s is not a tools/ra89r.py sidecar" % meta_path)
    off = len(MAGIC)
    baseline, base, size, nrec = struct.unpack_from("<BIII", blob, off)
    if data.__len__() != size:
        raise SystemExit("image is %d bytes, sidecar says %d" % (len(data), size))
    return data, base


def emit(name, table, first, last, stride, pages, out_dir):
    path = os.path.join(out_dir, name + ".c")
    with open(path, "w") as f:
        f.write("/* Generated by firmware/tools/extract_fonts.py -- do not edit.\n"
                " * Bitmap font lifted from the stock RA89R firmware (see docs/ra89r_lcd.md):\n"
                " * chars 0x%02X-0x%02X, %d columns x %d pages, column-major,\n"
                " * page-major, bit 0 of each byte = topmost pixel of that page.\n */\n"
                % (first, last, stride, pages))
        f.write('#include "driver/fonts.h"\n\n')
        f.write("const uint8_t %s_glyphs[] = {\n" % name)
        per_line = 16
        for i in range(0, len(table), per_line):
            chunk = table[i:i + per_line]
            f.write("    " + " ".join("0x%02X," % b for b in chunk) + "\n")
        f.write("};\n\n")
        f.write("const font_t %s = { %d, %d, %d, %d, %d, %s_glyphs };\n"
                % (name, first, last, stride, pages, stride * pages, name))
    print("wrote %s (%d glyphs, %d bytes)" % (path, last - first + 1, len(table)))


def main(argv=None):
    ap = argparse.ArgumentParser(description="extract the stock RA89R fonts")
    ap.add_argument("image", help="decoded image (needs the .meta sidecar)")
    ap.add_argument("--meta")
    ap.add_argument("--outdir",
                    default=os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                         "..", "App", "driver"))
    a = ap.parse_args(argv)

    data, base = load(a.image, a.meta)
    out_dir = os.path.abspath(a.outdir)
    for name, addr, first, last, stride, pages in FONTS:
        n = last - first + 1
        off = addr - base
        if off < 0 or off + n * stride * pages > len(data):
            raise SystemExit("%s: 0x%08X is outside the image" % (name, addr))
        emit(name, data[off:off + n * stride * pages], first, last, stride, pages,
             out_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
